name: Linting

# Trigger each time HEAD branch is updated in a pull request
# see https://github.com/orgs/community/discussions/26366
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:

  eslint:
      name: ESLint (JS)
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 2 # to also fetch parent of PR (used to get changed files)

        - name: Get changed files
          id: ts-changed
          uses: ./.github/actions/changed_files/
          with:
            file-extensions: \.js$|\.mjs$|\.ts$

        - name: Setup Node.js
          if: ${{ steps.ts-changed.outputs.changed-files != ''}}
          uses: actions/setup-node@v4
          with:
            node-version: '20' # End of Life (EOL): April 2026
            cache: 'npm'

        - name: Install dependencies
          if: ${{ steps.ts-changed.outputs.changed-files != ''}}
          run: npm install

        # with ESLint v9 --ignore-path does not exist anymore
        # see [1] for the PR. However, my feeling for this is totally reflected
        # by [2]. Hopefully, it will come back in future versions.
        # [1] https://github.com/eslint/eslint/pull/16355
        # [2] https://github.com/eslint/eslint/issues/16264#issuecomment-1292858747
        - name: Run ESLint
          if: ${{ steps.ts-changed.outputs.changed-files != ''}}
          run: |
            echo "🚨 Running ESLint version: $(npx --quiet eslint --version)"
            npx eslint --config ./.config/eslint.mjs --max-warnings 0 --no-warn-ignored ${{ steps.ts-changed.outputs.changed-files }}
